#!/usr/bin/env bash

set -e
set -x

helm repo add artifactory https://artifactory.delivery.puppetlabs.net/artifactory/helm__local
cd /apps/helm-charts/vmpooler
helm dependency update
cd /apps/docs
helm package ../helm-charts/*
helm repo index --url https://puppetlabs.github.io/vmpooler-deployment .

