#!/usr/bin/env bash

docker run --rm -it -v $(pwd):/apps --entrypoint /bin/sh alpine/helm \
  -c 'helm repo add artifactory https://artifactory.delivery.puppetlabs.net/artifactory/helm__local && cd /apps/helm-charts/vmpooler && helm dependency update'
