# For local development of vmpooler core and provider gems instead of using a
# git source ensure the following directory structure:
# |-- vmpooler-projects
# |  |--vmpooler-deployment
# |  |--vmpooler-provider-ec2
# |  |--vmpooler-provider-gce
# |  |--vmpooler-provider-vsphere
#
# Then change directory into vmpooler-projects and build with: 


FROM jruby:9.4.7.0-jdk11

LABEL org.opencontainers.image.description "VMPooler plus all known providers"

ENV DEBIAN_FRONTEND=noninteractive
ENV LOGFILE=/dev/stdout
ENV RACK_ENV=production

RUN apt-get update -qq && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends make git netbase && \
    apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

RUN gem install bundler

COPY docker-entrypoint.dev.sh /usr/local/bin/docker-entrypoint.sh

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

COPY Gemfile.dev ./Gemfile
COPY .rerun ./.rerun

RUN bundle config set --local jobs 3

ENTRYPOINT ["docker-entrypoint.sh"]
