apiVersion: v2
name: vmpooler
description: A Helm chart to deploy vmpooler
type: application
icon: https://github.com/puppetlabs/vmpooler/raw/master/lib/vmpooler/public/img/logo.png
version: 3.10.2
appVersion: 706714b98a2739efe51d256c86dcad1385334b3e
dependencies:
  - name: redis
    repository: https://artifactory.delivery.puppetlabs.net/artifactory/helm__local
    version: 16.13.2
