apiVersion: v2
name: vmpooler
description: A Helm chart to deploy vmpooler
type: application
icon: https://github.com/puppetlabs/vmpooler/raw/master/lib/vmpooler/public/img/logo.png
version: 3.1.0-rc.3
appVersion: pr105-f41a5f83e93a4da560bb2df7a1ce950f0ec7bb70
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.11.3
